const e=JSON.parse('{"key":"v-c52e25d6","path":"/posts/9e235953.html","title":"Flutter 中的异常处理","lang":"zh-CN","frontmatter":{"permalink":"/posts/9e235953.html","title":"Flutter 中的异常处理","abbrlink":"9e235953","date":"2021-07-29T07:41:47.000Z","updated":"2023-12-30T08:17:02.000Z","tag":"flutter","description":"说明 FLutter中的错误不会导致应用程序奔溃，只会终止执行出错代码之后的逻辑，在导致Widget.build()返回为null的错误会导致Widget构建失败，并返回红底黄字的错误原因Widget（在 Release 模式则会显示为灰底区域）；一般来说，Flutter 中的错误都会被FlutterError.onError捕获并处理；对于异步方法产生异常等Flutter框架没有捕获的情况，会交由当前代码所在的Zone处理（这些异常可以使用runZonedGuarded捕获并处理）。","head":[["meta",{"property":"og:url","content":"https://jixiaoyong.github.io/blog/posts/9e235953.html"}],["meta",{"property":"og:site_name","content":"JI,XIAOYONG"}],["meta",{"property":"og:title","content":"Flutter 中的异常处理"}],["meta",{"property":"og:description","content":"说明 FLutter中的错误不会导致应用程序奔溃，只会终止执行出错代码之后的逻辑，在导致Widget.build()返回为null的错误会导致Widget构建失败，并返回红底黄字的错误原因Widget（在 Release 模式则会显示为灰底区域）；一般来说，Flutter 中的错误都会被FlutterError.onError捕获并处理；对于异步方法产生异常等Flutter框架没有捕获的情况，会交由当前代码所在的Zone处理（这些异常可以使用runZonedGuarded捕获并处理）。"}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2024-01-01T15:46:34.000Z"}],["meta",{"property":"article:author","content":"JI,XIAOYONG"}],["meta",{"property":"article:tag","content":"flutter"}],["meta",{"property":"article:published_time","content":"2021-07-29T07:41:47.000Z"}],["meta",{"property":"article:modified_time","content":"2024-01-01T15:46:34.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"Flutter 中的异常处理\\",\\"image\\":[\\"\\"],\\"datePublished\\":\\"2021-07-29T07:41:47.000Z\\",\\"dateModified\\":\\"2024-01-01T15:46:34.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"JI,XIAOYONG\\",\\"url\\":\\"https://jixiaoyong.github.io\\"}]}"]]},"headers":[{"level":2,"title":"说明","slug":"说明","link":"#说明","children":[]},{"level":2,"title":"详细说明","slug":"详细说明","link":"#详细说明","children":[{"level":3,"title":"try...catch","slug":"try-catch","link":"#try-catch","children":[]},{"level":3,"title":"ErrorWidget.builder","slug":"errorwidget-builder","link":"#errorwidget-builder","children":[]},{"level":3,"title":"FlutterError.onError","slug":"fluttererror-onerror","link":"#fluttererror-onerror","children":[]},{"level":3,"title":"runZonedGuarded(onError)","slug":"runzonedguarded-onerror","link":"#runzonedguarded-onerror","children":[]}]},{"level":2,"title":"参考文章","slug":"参考文章","link":"#参考文章","children":[]}],"git":{"createdTime":1680852645000,"updatedTime":1704123994000,"contributors":[{"name":"jixiaoyong","email":"jixiaoyong1995@gmail.com","commits":3}]},"readingTime":{"minutes":3.77,"words":1132},"filePathRelative":"_posts/Flutter_Handle_Error.md","localizedDate":"2021年7月29日","excerpt":"<h2> 说明</h2>\\n<p><code>FLutter</code>中的错误不会导致应用程序奔溃，只会终止执行出错代码之后的逻辑，在导致<code>Widget.build()</code>返回为<code>null</code>的错误会导致<code>Widget</code>构建失败，并返回<em>红底黄字</em>的错误原因<code>Widget</code>（在 Release 模式则会显示为<em>灰底区域</em>）；一般来说，Flutter 中的错误都会被<code>FlutterError.onError</code>捕获并处理；对于异步方法产生异常等<code>Flutter框架</code>没有捕获的情况，会交由当前代码所在的<code>Zone</code>处理（这些异常可以使用<code>runZonedGuarded</code>捕获并处理）。</p>","autoDesc":true}');export{e as data};
